[local]
localhost

[mongodb]
mongodb.nagavarapu.online

[catalogue]
catalogue.nagavarapu.online


[frontend]
frontend.nagavarapu.online

[redis]
redis.nagavarapu.online

[user]
user.nagavarapu.online

[cart]
cart.nagavarapu.online